### ISSUE TITLE
ModuleNotFoundError: No module named 'DankCord.objects'

### ISSUE THREAD

**Issue by Jivesh-Bisht** [Sxvxgee/WhiteFlow#5]
When i git clone the repo and then edit the example_config.toml and then install the requirement and run the main.py file i get this error saying

`Traceback (most recent call last):
  File "/home/jivesh/WhiteFlow/Source/main.py", line 7, in <module>
    from internal.botbase import Bot
  File "/home/jivesh/WhiteFlow/Source/internal/botbase.py", line 9, in <module>
    from DankCord.objects import Message, Button, Dropdown
ModuleNotFoundError: No module named 'DankCord.objects'`

Also the requirements.txt is incomplete

It lacks these packages (separated by a space)
`websocket-client websocket orjson requests`

**Comment by Jivesh-Bisht** [comment]
Nvm i got that thing working, just remove the `.objects` part and it will work fine

**Comment by Jivesh-Bisht** [comment]
Running the bot gives a lot of errors and doesn't work so if you want to run the autofarmer then you gotta wait for the development to finish or fix the issues yourself.
